language: cpp
services:
  - docker
before_install:
  - docker pull ddennedy/shotcut-build
script:
  - docker run -v $PWD:/root/shotcut ddennedy/shotcut-build mltframework/shotcut/scripts/build-shotcut.sh
  - ls -ltr
