language: cpp
services:
  - docker
before_install:
  - docker pull ddennedy/shotcut-build
script:
  - export VERSION=$(date +"%y%m%d")
  - echo "VERSION = $VERSION"
  - docker run -v $PWD/scripts:/root/shotcut ddennedy/shotcut-build ./build-shotcut.sh
  - mkdir deploy
  - cp scripts/shotcut.txz deploy/shotcut-linux-x86_64-$VERSION.txz
  - cp scripts/src.tar.xz deploy/shotcut-src-$VERSION.txz
  - ls -lh deploy
deploy:
  provider: s3
  edge: true
  local_dir: ./deploy
  bucket: "builds.us.meltytech"
  upload_dir: shotcut
  storage_class: REDUCED_REDUNDANCY
  on:
    branch: travis
