language: cpp
services:
  - docker
before_install:
  - docker pull ddennedy/shotcut-build
script:
  - export VERSION=$(date +"%y%m%d")
  - echo "VERSION = $VERSION"
#  - docker run -v $PWD/scripts:/root/shotcut ddennedy/shotcut-build ./build-shotcut.sh
  - ls -ltrF scripts
#  - mkdir deploy
#  - mv scripts/shotcut/shotcut.txz deploy/shotcut-linux-x86_64-$VERSION.txz
#  - mv scripts/shotcut/src.tar.xz deploy/shotcut-src-$VERSION.txz
deploy:
  - provider: s3
  - edge: true
  - local_dir: ./deploy
  - bucket: "builds.us.meltytech"
  - upload_dir: shotcut
  - storage_class: REDUCED_REDUNDANCY
